### ISSUE TITLE
unable to install plugin from composer

### ISSUE THREAD

**Issue by dhananjayve** [cakemanager/cakephp-whosonline#2]
I had used composer to install plugin
composer require cakemanager/cakephp-whosonline

But i got following error:
  Problem 1
    - Installation request for cakemanager/cakephp-whosonline ^1.0@RC -> satisfiable by cakemanager/cakephp-whosonline[1.0.0-rc1].
    - cakemanager/cakephp-whosonline 1.0.0-rc1 requires cakemanager/cakephp-cakemanager 1.0.x-dev -> no matching package found.

I had already installed cakemanager dev-master
Please suggest

**Comment by bobmulder** [comment]
Hi @dhananjayve,

Since the CakeManager plugin is deprecated, I haven't updated the plugin for CakeAdmin.
[CakeAdmin](https://github.com/cakemanager/cakephp-cakeadmin) replaces the CakeManager plugin. 

Tonight I will update the plugin to CakeAdmin so you will be able to use it. Okay?

Thanks for noticing!

**Comment by dhananjayve** [comment]
OK Thank You

**Comment by bobmulder** [comment]
Hi @dhananjayve,

I took a look at the plugin. As I said before, this plugin works smooth with the CakeManger plugin, however its deprecated. So I planned to deprecate this plugin as well. 

However, the goal of this plugin is also managed in https://github.com/cakemanager/cakephp-analyzer. So in fact that plugin is the restart and rebuild of this plugin, built on CakeAdmin.

I admit, the plugin is not stable at al, but you can try something with it, and contributions are always more than welcome!

If you have more questions, feel free to ask!

You can find me at Gitter as well: https://gitter.im/bobmulder.

Greetz,

Bob

**Comment by dhananjayve** [comment]
Analyzer is under development ans plugin is not stable yet. So I think its better to contribute than to wait a stable version of analyzer. soon I will connect with you. However I am very new for open source projects.

**Comment by bobmulder** [comment]
I would advise you to take a look at https://github.com/cakemanager/cakephp-cakeadmin. I think it would help you!
